### ISSUE TITLE
The parameter for smooth and DFT321

### ISSUE THREAD

**Issue by fuyimin96** [htzheng/HapticVisualFCN#1]
Hello, where is the parameter for smooth (cutoff) and the fs for DFT321

**Comment by fuyimin96** [comment]
Thanks and waiting for your reply

**Comment by htzheng** [comment]
Sorry, the code is released a long time ago and I cannot find the related pre-processing code. However, I think you even if with the default setting, deep learning-based approach should be able to achieve good results.
